### ISSUE TITLE
Solr should not destroy my queries

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.solr#41]
It seems that the query processing of ftw.solr or collective.solr modifies the query inplace.
The query is afterwards broken.

Example:

``` python
>>> query = {'path': {'query': '/', 'limit': -1}, 'SearchableText': 'test*'}
>>> len(portal_catalog(query))
0
>>> len(portal_catalog(query))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zope/cache/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/monkey.py", line 84, in searchResults
    return self.__af_old_searchResults(REQUEST, **kw)
  File "/home/zope/cache/eggs/collective.solr-3.0-py2.7.egg/collective/solr/monkey.py", line 31, in searchResults
    return adapter(REQUEST, **kw)
  File "/home/zope/cache/eggs/collective.solr-3.0-py2.7.egg/collective/solr/dispatcher.py", line 42, in __call__
    return solrSearchResults(request, **keywords)
  File "/home/zope/cache/eggs/collective.solr-3.0-py2.7.egg/collective/solr/dispatcher.py", line 86, in solrSearchResults
    mangleQuery(args, config, schema)
  File "/home/zope/cache/eggs/ftw.solr-1.3.1-py2.7.egg/ftw/solr/patches/mangler.py", line 76, in mangleQuery
    keywords[key] = value['query']
KeyError: 'query'
>>> query
{'path': {'limit': -1}, 'SearchableText': 'test*'}
```

versions:
- ftw.solr 1.3.1
- collective.solr 3.0

**Comment by mbaechtold** [comment]
@jone, is this still an issue?
